# Generated by Django 3.1 on 2021-03-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioBookID', models.IntegerField()),
                ('audioBookTitle', models.CharField(max_length=100)),
                ('audioBookAuthor', models.CharField(max_length=100)),
                ('audioBookNarrator', models.CharField(max_length=100)),
                ('audioBookDuration', models.TimeField()),
                ('audioBookUploaded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='songFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sondID', models.IntegerField()),
                ('songName', models.CharField(max_length=100)),
                ('songDuration', models.TimeField()),
                ('songUploaded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='podcastFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podID', models.IntegerField()),
                ('podName', models.CharField(max_length=100)),
                ('podDuration', models.TimeField()),
                ('podUploaded', models.DateTimeField()),
                ('podHost', models.CharField(max_length=100)),
                ('podParticipants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioApi.participants')),
            ],
        ),
    ]
