# Generated by Django 3.1 on 2021-03-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='part',
            new_name='name',
        ),
    ]
